### PR TITLE
Merge summaries

### PR DESCRIPTION
**Pull request by tonyhutter**
Just testing, please ignore

### CODE REVIEW

**Comment by mcmilk** [comment]
Thank you a lot, I will use it.

**Comment by mcmilk** [comment]
The FresBSD images have the repository now: https://github.com/mcmilk/openzfs-freebsd-images/releases

**Comment by mcmilk** [comment]
FreeBSD 13 has problems with the virtio nic. Just use the e1000 nic, like I gave done it here: https://github.com/mcmilk/zfs/tree/qemu-machines2

**Comment by mcmilk** [comment]
> FreeBSD 13 has problems with the virtio nic. Just use the e1000 nic, like I gave done it here: https://github.com/mcmilk/zfs/tree/qemu-machines2

Ah, some other problem :(

**Comment by mcmilk** [comment]
With your patch "ZTS: Add timeout to cp_stress" the tests are working fine: https://github.com/mcmilk/zfs/actions/runs/9987143530/job/27600944835

Would be nice, if this cp_stress patch gets merged. I will update the ZTS PR then.

I will update this also: https://github.com/tonyhutter/zfs/compare/c52d71fc39039aae85cbec8c2f8e07e29976d06a..2493ba265e02e8cce071d0607305d6117f662751

**Comment by mcmilk** [comment]
Looks good: https://github.com/mcmilk/zfs/actions/runs/10065520622

**Comment by tonyhutter** [comment]
That's good!  Now I need to add the merged summary into the runner test results, and try the test run on all the OSs.

**Comment by mcmilk** [comment]
Should come in around 2 hours there.
But it looks, like the OOM errors on fedora/almalinux are away, but not the `zfs_copies_006_pos` thing on FreeBSD :(

I am going to bed now, but it looks, that the thing gets ready somehow in the near future ;)

**Comment by tonyhutter** [comment]
@mcmilk I see that `zfs_copies_006_pos` passed in FreeBSD 13 with https://github.com/openzfs/zfs/pull/16379.  Maybe it's a fix?

**Comment by mcmilk** [comment]
> @mcmilk I see that `zfs_copies_006_pos` passed in FreeBSD 13 with [openzfs#16379](https://github.com/openzfs/zfs/pull/16379). Maybe it's a fix?

I debugged it here myself here: https://github.com/mcmilk/zfs/actions/runs/10078595389
The solution with the sync works, I found it also... was short before creating my own pull request, I have seen then the other pull request ;)

**Comment by tonyhutter** [comment]
@mcmilk we're doing better on the test runs now, but I need to account for failed tests re-running:
```
$ cat vm2log.txt | grep threa
Test: /usr/local/share/zfs/zfs-tests/tests/functional/append/threadsappend_001_pos (run as root) [00:00] [FAIL]
Test: /usr/local/share/zfs/zfs-tests/tests/functional/append/threadsappend_001_pos (run as root) [00:00] [PASS]
```
In those cases the log files in `vm*/current/log` will only show the single, re-ran, test rather than the hundreds of other tests that it previously did.  Example: https://github.com/tonyhutter/zfs/actions/runs/10082911976/artifacts/1736990191

**Comment by tonyhutter** [comment]
> I need to account for failed tests re-running

I just removed the `-R` flag.  I think that's the simplest solution. You can always manually re-run the test suite via the button on the  github runners webpage.

**Comment by mcmilk** [comment]
> > I need to account for failed tests re-running
> 
> I just removed the `-R` flag. I think that's the simplest solution. You can always manually re-run the test suite via the button on the github runners webpage.

I removed the `-R` flag already... with a small comment for explainig why: https://github.com/openzfs/zfs/blob/bf54607e667c078f9afc7f75fcb9c0c43591af22/.github/workflows/scripts/qemu-6-tests.sh

**Comment by mcmilk** [comment]
I would like to integrate ppc64le runners also this way:


The arm64 based runners have very slow disks. The module build takes hours there... but the ppc64 ones are really fast.
We have 7x ppc64le-ubuntu-24 runners. Each of them has: 4x cpu, 8GB RAM, 150GB free ssd space with 2000MB/s.

I would try to run there also our own qemu ... and then we can choose 7 different default systems:
- almalinux 8+9 (ppcle64)
- debian 12 (ppc64le)
- freebsd 13+14 (ppc64)
- freebsd 13+14 (ppc64le)

**Comment by tonyhutter** [comment]
Well, we only have a limited number of runners available, and we would want them prioritized for the normal x86-64 builders for now.  That said, maybe native ARM and PPC runners (non-VM) could be useful just to do a test build + and to run the shorter `santiy.run` test list.  We could add that later on as a separate PR though after this one gets in first.

**Comment by mcmilk** [comment]
> Well, we only have a limited number of runners available, and we would want them prioritized for the normal x86-64 builders for now. That said, maybe native ARM and PPC runners (non-VM) could be useful just to do a test build + and to run the shorter `santiy.run` test list. We could add that later on as a separate PR though after this one gets in first.

The ARM and PPC runners are hosted extern ... so they do not count I think.
Public open source repos have 20 github action runners.

**Comment by tonyhutter** [comment]
Looks like native ARM github runners are in beta testing:
https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/

**Comment by tonyhutter** [comment]
I think for now let's just get this working 100% with the normal x86-64 runners, and then we can add more github or self-hosted runners in a follow-on PR.

**Comment by tonyhutter** [comment]
Oh wow, the might have gone live with the ARM runners two days ago :+1: 
https://github.blog/news-insights/product-news/arm64-on-github-actions-powering-faster-more-efficient-build-systems/

**Comment by mcmilk** [comment]
Each Step within the Github Action workflow needs to finish in under 3 hours.
Thats why the runs look sometimes bad.... it would be nice if we had 32 GB RAM ;-)

https://github.com/mcmilk/zfs/actions/runs/10130341246/

**Comment by tonyhutter** [comment]
@mcmilk I'm seeing some runs that look like they complete, but don't have vm2's logs for some reason.   For example, https://github.com/tonyhutter/zfs/actions/runs/10171880645/job/28133617407?pr=1 looks like "success" but the FAIL counts in the summary are wrong.  When I look into it more, it looks like vm2 is missing a bunch of the ZTS log files, like:
```
$ ls vm1/current/
acl  channel_program  cli_root  cli_user  features  functional  local-rw-0-verify.state  log  perf_data  results  zvol

$ ls vm2/current/
log
```
I'm still looking into it.

**Comment by mcmilk** [comment]
> @mcmilk I'm seeing some runs that look like they complete, but don't have vm2's logs for some reason. For example, https://github.com/tonyhutter/zfs/actions/runs/10171880645/job/28133617407?pr=1 looks like "success" but the FAIL counts in the summary are wrong. When I look into it more, it looks like vm2 is missing a bunch of the ZTS log files, like:
> 
> ```
> $ ls vm1/current/
> acl  channel_program  cli_root  cli_user  features  functional  local-rw-0-verify.state  log  perf_data  results  zvol
> 
> $ ls vm2/current/
> log
> ```
> 
> I'm still looking into it.

There is a `KDB: stack backtrace: ... ` - so maybe the kernel did a reboot?
We should also take care for these files: `zdb.core` `zfs.core` `zpool.core`
When they exist, we should expect test failures ... even if the test looks okay.

Also seen on my tests:
vm1 kernel: pid 795 (file_write), uid 0 inumber 10 on /var/tmp/testdir: filesystem full

I am trying 60GB Disks now.

Looks mainly good: https://github.com/mcmilk/zfs/actions/runs/10200818925

**Comment by tonyhutter** [comment]
@mcmilk thanks for the tip. Looks like I need to re-base my change on your latest commit.  Should I rebase on `qemu-machines3`?

**Comment by mcmilk** [comment]
> @mcmilk thanks for the tip. Looks like I need to re-base my change on your latest commit. Should I rebase on `qemu-machines3`?

Yes, I am working on the `qemu-machines3` branch.

**Comment by mcmilk** [comment]
Ubuntu 20.04 fails on `zfs_copies_006_pos` ... a single sync fixes this, but I don't know why.
`zfs destroy` should work without syncing first - or I am wrong?

```
--- a/tests/zfs-tests/tests/functional/cli_root/zfs_copies/zfs_copies.kshlib
+++ b/tests/zfs-tests/tests/functional/cli_root/zfs_copies/zfs_copies.kshlib
@@ -153,5 +153,6 @@ function do_vol_test
                log_must umount $mntp
        fi
 
+       sync
        log_must zfs destroy $vol
 }

```

**Comment by mcmilk** [comment]
`send_encrypted_freeobjects` is new since one or two days... I didn't go into detail, but it fails on FreeBSD an Linux :(

**Comment by tonyhutter** [comment]
.> send_encrypted_freeobjects is new since one or two days... I didn't go into detail, but it fails on FreeBSD an Linux :(

@mcmilk thanks, we'll keep an eye on that one.  I've rebased on qemu-machines3 with my changes and am testing it.

**Comment by tonyhutter** [comment]
Quality of life feature - my latest push added the link to the log artifacts below the test results:
```
...
Tests with results other than PASS that are unexpected:
    FAIL fault/auto_replace_002_pos (expected PASS)
Full logs for download:
https://github.com/tonyhutter/zfs/actions/runs/10221662252/artifacts/1771217597
Error: Process completed with exit code 1.
```

**Comment by tonyhutter** [comment]
@mcmilk the `zpool_status_008_pos` failures are just timing.  This fixes it:
```diff
diff --git a/tests/zfs-tests/tests/functional/cli_root/zpool_status/zpool_status_008_pos.ksh b/tests/zfs-tests/tests/functional/cli_root/zpool_status/zpool_status_008_pos.ksh
index 6be2ad5a7..70f480cbb 100755
--- a/tests/zfs-tests/tests/functional/cli_root/zpool_status/zpool_status_008_pos.ksh
+++ b/tests/zfs-tests/tests/functional/cli_root/zpool_status/zpool_status_008_pos.ksh
@@ -69,12 +69,12 @@ for raid_type in "draid2:3d:6c:1s" "raidz2"; do
        log_mustnot eval "zpool status -e $TESTPOOL2 | grep ONLINE"
 
        # Check no ONLINE slow vdevs are show.  Then mark IOs greater than
-       # 10ms slow, delay IOs 20ms to vdev6, check slow IOs.
+       # 40ms slow, delay IOs 80ms to vdev6, check slow IOs.
        log_must check_vdev_state $TESTPOOL2 $TESTDIR/vdev6 "ONLINE"
        log_mustnot eval "zpool status -es $TESTPOOL2 | grep ONLINE"
 
-       log_must set_tunable64 ZIO_SLOW_IO_MS 10
-       log_must zinject -d $TESTDIR/vdev6 -D20:100 $TESTPOOL2
+       log_must set_tunable64 ZIO_SLOW_IO_MS 40
+       log_must zinject -d $TESTDIR/vdev6 -D80:100 $TESTPOOL2
        log_must mkfile 1048576 /$TESTPOOL2/testfile
        sync_pool $TESTPOOL2
        log_must set_tunable64 ZIO_SLOW_IO_MS $OLD_SLOW_IO
```
I'm still trying to figure out why `raidz_expand_001_pos.ksh` is reporting errors.  That seems to be the last test that is failing on QEMU.

**Comment by mcmilk** [comment]
```
20240806T173422/results:Test: /usr/share/zfs/zfs-tests/tests/functional/raidz/raidz_expand_001_pos.ksh (run as root) [01:15] [PASS]
20240806T173539/results:Test: /usr/share/zfs/zfs-tests/tests/functional/raidz/raidz_expand_001_pos.ksh (run as root) [00:53] [PASS]
20240806T173633/results:Test: /usr/share/zfs/zfs-tests/tests/functional/raidz/raidz_expand_001_pos.ksh (run as root) [01:19] [PASS]
20240806T173755/results:Test: /usr/share/zfs/zfs-tests/tests/functional/raidz/raidz_expand_001_pos.ksh (run as root) [03:14] [PASS]
20240806T174243/results:Test: /usr/share/zfs/zfs-tests/tests/functional/raidz/raidz_expand_001_pos.ksh (run as root) [02:19] [PASS]
20240806T174503/results:Test: /usr/share/zfs/zfs-tests/tests/functional/raidz/raidz_expand_001_pos.ksh (run as root) [00:55] [PASS]
[root@vm1 test_results]# grep -r ".*raidz_expand_001_pos.ksh.*\[FAIL\]$"|grep result
20240806T170150/results:Test: /usr/share/zfs/zfs-tests/tests/functional/raidz/raidz_expand_001_pos.ksh (run as root) [02:55] [FAIL]
20240806T170812/results:Test: /usr/share/zfs/zfs-tests/tests/functional/raidz/raidz_expand_001_pos.ksh (run as root) [02:57] [FAIL]
20240806T172246/results:Test: /usr/share/zfs/zfs-tests/tests/functional/raidz/raidz_expand_001_pos.ksh (run as root) [03:04] [FAIL]
20240806T173017/results:Test: /usr/share/zfs/zfs-tests/tests/functional/raidz/raidz_expand_001_pos.ksh (run as root) [03:02] [FAIL]
20240806T174111/results:Test: /usr/share/zfs/zfs-tests/tests/functional/raidz/raidz_expand_001_pos.ksh (run as root) [01:29] [FAIL]
[root@vm1 test_results]# grep -r ".*raidz_expand_001_pos.ksh.*\[FAIL\]$"|grep result |wc -l
5
[root@vm1 test_results]# grep -r ".*raidz_expand_001_pos.ksh.*\[PASS\]$"|grep result |wc -l
40
```

The error comes from the command `zpool scrub -w testpool` within the ksh function `test_scrub`:

```
SUCCESS: zpool import -o cachefile=none -d /var/tmp testpool
SUCCESS: zpool scrub -w testpool
SUCCESS: zpool clear testpool
SUCCESS: zpool export testpool
124+0 records in
124+0 records out
130023424 bytes (130 MB, 124 MiB) copied, 0.295698 s, 440 MB/s
124+0 records in
124+0 records out
130023424 bytes (130 MB, 124 MiB) copied, 0.266317 s, 488 MB/s
124+0 records in
124+0 records out
130023424 bytes (130 MB, 124 MiB) copied, 0.198369 s, 655 MB/s
SUCCESS: zpool import -o cachefile=none -d /var/tmp testpool
SUCCESS: zpool scrub -w testpool
ERROR: check_pool_status testpool errors No known data errors exited 1
NOTE: Performing test-fail callback (/usr/share/zfs/zfs-tests/callbacks/zfs_dbgmsg.ksh)
```

I think. the `scrub -w` wants start scrubbing on a pool, which does this already.

Option 1: check the status first, and if already some a scrub started, than just wait for it
Option 2: always stop scrubbing via `zpool scrub -s` and ignore the exit status of it

What would you prefer?

**Comment by tonyhutter** [comment]
@mcmilk I'm currently testing with this:
```diff
diff --git a/tests/zfs-tests/tests/functional/raidz/raidz_expand_001_pos.ksh b/tests/zfs-tests/tests/functional/raidz/raidz_expand_001_pos.ksh
index 063d7fa73..167f39cfc 100755
--- a/tests/zfs-tests/tests/functional/raidz/raidz_expand_001_pos.ksh
+++ b/tests/zfs-tests/tests/functional/raidz/raidz_expand_001_pos.ksh
@@ -153,8 +153,12 @@ function test_scrub # <pool> <parity> <dir>
        done
 
        log_must zpool import -o cachefile=none -d $dir $pool
+       if is_pool_scrubbing $pool ; then
+               wait_scrubbed $pool
+       fi
 
        log_must zpool scrub -w $pool
+
        log_must zpool clear $pool
        log_must zpool export $pool
 
@@ -165,7 +169,9 @@ function test_scrub # <pool> <parity> <dir>
        done
 
        log_must zpool import -o cachefile=none -d $dir $pool
-
+       if is_pool_scrubbing $pool ; then
+               wait_scrubbed $pool
+       fi
        log_must zpool scrub -w $pool
 
        log_must check_pool_status $pool "errors" "No known data errors"
diff --git a/tests/zfs-tests/tests/functional/raidz/raidz_expand_002_pos.ksh b/tests/zfs-tests/tests/functional/raidz/raidz_expand_002_pos.ksh
index 004f3d1f9..e416926d1 100755
--- a/tests/zfs-tests/tests/functional/raidz/raidz_expand_002_pos.ksh
+++ b/tests/zfs-tests/tests/functional/raidz/raidz_expand_002_pos.ksh
@@ -105,6 +105,10 @@ for disk in ${disks[$(($nparity+2))..$devs]}; do
                log_fail "pool $pool not expanded"
        fi
 
+       # It's possible the pool could be auto scrubbing here.  If so, wait.
+       if is_pool_scrubbing $pool ; then
+               wait_scrubbed $pool
+       fi
        verify_pool $pool
 
        pool_size=$expand_size
```
I think that might help some of the `raidz_expand_001_pos` failures, but not eliminate it completely.   There may actually be a legitimate problem that's just being exposed but I'm not sure yet.  I want to get some more test runs done to see.

Also, I tweaked my commit a little to add more time in `zpool_status_008_pos` and fix a rare timing bug in `crtime_001_pos`.

**Comment by mcmilk** [comment]
> @mcmilk I'm currently testing with this:
> 
> ```diff
> diff --git a/tests/zfs-tests/tests/functional/raidz/raidz_expand_001_pos.ksh b/tests/zfs-tests/tests/functional/raidz/raidz_expand_001_pos.ksh
> index 063d7fa73..167f39cfc 100755
> --- a/tests/zfs-tests/tests/functional/raidz/raidz_expand_001_pos.ksh
> +++ b/tests/zfs-tests/tests/functional/raidz/raidz_expand_001_pos.ksh
> @@ -153,8 +153,12 @@ function test_scrub # <pool> <parity> <dir>
>         done
>  
>         log_must zpool import -o cachefile=none -d $dir $pool
> +       if is_pool_scrubbing $pool ; then
> +               wait_scrubbed $pool
> +       fi
>  
>         log_must zpool scrub -w $pool
> +
>         log_must zpool clear $pool
>         log_must zpool export $pool
>  
> @@ -165,7 +169,9 @@ function test_scrub # <pool> <parity> <dir>
>         done
>  
>         log_must zpool import -o cachefile=none -d $dir $pool
> -
> +       if is_pool_scrubbing $pool ; then
> +               wait_scrubbed $pool
> +       fi
>         log_must zpool scrub -w $pool
>  
>         log_must check_pool_status $pool "errors" "No known data errors"
> diff --git a/tests/zfs-tests/tests/functional/raidz/raidz_expand_002_pos.ksh b/tests/zfs-tests/tests/functional/raidz/raidz_expand_002_pos.ksh
> index 004f3d1f9..e416926d1 100755
> --- a/tests/zfs-tests/tests/functional/raidz/raidz_expand_002_pos.ksh
> +++ b/tests/zfs-tests/tests/functional/raidz/raidz_expand_002_pos.ksh
> @@ -105,6 +105,10 @@ for disk in ${disks[$(($nparity+2))..$devs]}; do
>                 log_fail "pool $pool not expanded"
>         fi
>  
> +       # It's possible the pool could be auto scrubbing here.  If so, wait.
> +       if is_pool_scrubbing $pool ; then
> +               wait_scrubbed $pool
> +       fi
>         verify_pool $pool
>  
>         pool_size=$expand_size
> ```
> 
> I think that might help some of the `raidz_expand_001_pos` failures, but not eliminate it completely. There may actually be a legitimate problem that's just being exposed but I'm not sure yet. I want to get some more test runs done to see.
> 
> Also, I tweaked my commit a little to add more time in `zpool_status_008_pos` and fix a rare timing bug in `crtime_001_pos`.

I will test run this with a for loop, I think 50 times should be a good start.
Only these two via `-t raidz_expand_001_pos + -t raidz_expand_002_pos`

It's running with -I 55 option:
https://github.com/mcmilk/zfs/actions/runs/10272187541

**Comment by mcmilk** [comment]
Hm, the `raidz_expand_001_pos` tests are failing, even if the wait for scrub thing :(

I used this `is_pool_scrubbing $pool && wait_scrubbed $pool`
Diff is here: https://github.com/openzfs/zfs/commit/02a14e7c0ff2cb15b2c151b66c05d1142f196967

**Comment by mcmilk** [comment]
Almalinux 8 ~~and Ubuntu 20.04~~ are fine.
Maybe it's bclone related - cause this is disabled on the older kernels?

**Comment by mcmilk** [comment]
Some points to the `raidz_expand_001_pos` testing problem:
- I limited the code to run only on scalar speed (exclude possible assembly failures)
- FreeBSD 13/14 does not have this issue et all, all tests run fine at around 2m 30s
- FreeBSD 15 does not have this issue et all, all tests run fine at around 4m
- on Linux 5.4: timings are around 3m and the faling test rate is: 1/120
- on Linux 6.x: timings are around 5m 30s and the faling test rate is: 1/2 maybe 1/3

Special test run with only `raidz_expand_001_pos`: https://github.com/mcmilk/zfs/actions/runs/10346648527

So the raid code is maybe okay... but some spl thing?
Should we run against zfs-2.2.5 ??

**Pull request closed without merging**
